title: Default
tabs:

  content:
    sections:
      content:
        type: fields
        fields:
          blocks:
            type: blocks
            fieldsets:
              - _carousel
              - _divider
              - _feature
              - _features
              - _heading
              - _image
              - _references
              - _text
              - _video

  seo:
    sections:
      seo:
        type: fields
        fields:
          seoTitle:
            type: text
          seoDescription:
            type: text
          seoImage:
            type: files
            multiple: false

  advanced:
    sections:
      pages:
        type: pages
      files:
        type: files

