title: Default
icon: 📄
columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          intro:
            type: textarea
            size: small
            buttons: false
          text:
            type: blocks

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

