title: Default
columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
          blocks:
            type: blocks
            fieldsets:
              - wht-2col
              - wht-enum
              - wht-hr
              - wht-txt
              - wht-yt
              - wht-img
              - wht-vid

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

