title: Default
columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          blocks:
            type: blocks
            fieldsets:
              - wht-txt
              - wht-features
              - wht-hr
              - wht-img
              - wht-vid
              - wht-h

  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

