title: Default
tabs:

  content:
    sections:
      content:
        type: fields
        fields:
          blocks:
            type: blocks
            fieldsets:
              - wht-txt
              - wht-refs
              - wht-feat
              - wht-feats
              - wht-hr
              - wht-img
              - wht-vid
              - wht-h
  seo:
    sections:
      seo:
        type: fields
        fields:
          seoTitle:
            type: text
          seoDescription:
            type: text
          seoImage:
            type: files
            multiple: false

  advanced:
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

