title: Site
tabs:
  content:
    sections:
      pages:
        type: pages
      globals:
        type: fields
        fields:
          menu_links:
            type: structure
            fields:
              label: 
                type: text
              url: 
                type: text
          footerLinks:
            type: structure
            fields:
              name: 
                type: text
              links:
                type: structure
                fields:
                  label: 
                    type: text
                  url: 
                    type: text
          legal:
            type: text
  seo:
    sections:
      seo:
        type: fields
        fields:
          seoImage:
            type: files
            multiple: false
  advanced:
    sections:
      files:
        type: files